---
title: "p8105_hw5_al3998"
author: "AimingLiu"
date: "10/31/2019"
output: github_document
editor_options: 
  chunk_output_type: console
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE,
                      warning = FALSE,
                      fig.width = 8, 
                      fig.height = 6,
                      out.width = "90%"
)
library(tidyverse)
library(dplyr)
library(rvest)
library(purrr)
library(broom)
```

```{r}
set.seed(10)
iris_with_missing = iris %>% 
  map_df(~replace(.x, sample(1:150, 20), NA)) %>%
  mutate(Species = as.character(Species)) %>% 
  janitor::clean_names()  
```
## Problem 1
### write the function
```{r}
  NAmean = function(x){
    if (is.numeric(x)){
    replace(x, is.na(x), mean(x, na.rm = TRUE))
    }else if(is.character(x)){
     replace(x, is.na(x), "virginica") 
    }
  }
```

```{r}
 output = vector("list", length = 5)
  for(i in 1:5){
    output[[i]] = NAmean(iris_with_missing[[i]])
  }
  output = map(iris_with_missing, NAmean)
  output
```
## Problem 2
```{r message=FALSE,warning = FALSE}
file_list = as.data.frame(list.files(path = "./data/", pattern="*.csv")) 
 colnames(file_list) =  "file_name"
```

```{r message=FALSE,warning = FALSE}
file_path =  "./data/"
read_file = function(file_name){
         read_csv(paste0(file_path, file_name))
         
}

output = purrr::map(file_list$file_name, read_file)
output
```

```{r message=FALSE,warning = FALSE}
file_nest = 
  file_list %>% 
  mutate(data = purrr::map(file_list$file_name, read_file)) %>% 
  unnest()
```

```{r message=FALSE,warning = FALSE}
  file_tidy = file_nest %>% 
  pivot_longer(week_1:week_8,
               names_to = "week",
               values_to = "data") %>% 
  mutate(file_name = str_remove(file_name, ".csv"),
         week = str_remove(week, "week_")) %>% 
  separate(file_name,into = c("group", "subject_id"), sep = "_") %>% 
  mutate(group = recode(group,"con"="control","exp" = "experimental"))
  ggplot(file_tidy,aes(x= week,y = data,color =subject_id,group = subject_id))+
  geom_point()+
  geom_line()+
  labs(
     title = "  observations on each subject over time",
     x = "week",
     y = "data"
  )+ theme(legend.position = "bottom")+
  facet_grid(~group)
```


Problem 3

```{r}
sim_regression = function(n = 30, beta0 = 2, beta1) {
  sim_data = tibble(
    x = rnorm(30, mean = 0, sd = 1),
    y = beta0 + beta1 * x + rnorm(30, 0, sqrt(50))
  )
  ls_fit = lm(y ~ x, data = sim_data)
  ls_tidy = broom::tidy(ls_fit)
  tibble(
   beta1_hat = ls_tidy$estimate[2],
   p_value = ls_tidy$p.value[2])
}


```

```{r}
set.seed(10)
output_b1 = rerun(10000, sim_regression(beta1 = 0)) %>% 
 bind_rows()

head(output_b1)
```

```{r}
beta_list = list("beta1_1"  = 1, 
                 "beta1_2"  = 2, 
                 "beta1_3"  = 3, 
                 "beta1_4"  = 4,
                 "beta1_5"  = 5,
                 "beta1_6"  = 6)
output = vector("list", length = 6)

for (i in 1:6) {
  output[[i]] = rerun(10000, sim_regression(beta1 = beta_list[[i]])) %>% 
    bind_rows
}
```

```{r}
beta_results = 
  tibble(beta1_value = c(1,2,3,4,5,6)) %>% 
  mutate(
    output_lists = map(.x = beta1_value, ~rerun(10000, sim_regression(beta1 = .x))),
    estimate_dfs = map(output_lists, bind_rows)) %>% 
  select(-output_lists) %>% 
  unnest(estimate_dfs)

  head(beta_results)
```

```{r}
  beta_sig = beta_results %>% 
  group_by(beta1_value) %>% 
  filter(p_value < 0.05) %>% 
  group_by(beta1_value) %>% 
  mutate(power = n()/10000) 
  plot = ggplot(beta_sig,aes(x = beta1_value,y = power))+
         geom_col()+
         labs(
    title = "Plot about the power about different beta1 value",
    x = "value of beta1",
    y = "power")
       
```


